name: schedule
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  reconcile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - run: scripts/reconcile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OBS_PASSWORD: ${{ secrets.OBS_PASSWORD }}
