name: schedule
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  reconcile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: scripts/reconcile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OBS_PASSWORD: ${{ secrets.OBS_PASSWORD }}
