name: schedule
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  reconcile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - run: scripts/reconcile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OBS_PASSWORD: ${{ secrets.OBS_PASSWORD }}
