name: schedule
on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'
jobs:
  reconcile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - run: scripts/reconcile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OBS_PASSWORD: ${{ secrets.OBS_PASSWORD }}
